### ISSUE TITLE
LuvOS - ACPI SPCR preconfigured baudrate handling

### ISSUE THREAD

**Issue by semihalf-wojtas-marcin** [ARM-software/arm-enterprise-acs#101]
Please cherry-pick the upstream Linux patch:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b413b1abeb21b4a152c0bf8d1379efa30759b6e3

It landed after v4.18.x release, which is used in the current version of the LuvOS kernel. It will allow to enable the OS console for the platforms that configure UART baudrate in firmware (such as Marvell Armada 7k8k or CN913x SoCs).

**Comment by edhay** [comment]
Hi Marcin,

    This patch is cherry picked by the following commit:
https://github.com/ARM-software/arm-enterprise-acs/commit/4889003cebf794b4d2bc2d2477eecc714b4364e5
And now is part of the build.
Hence, closing this issue.

-- Enterprise ACS Support
