### ISSUE TITLE
ERROR: Nothing RPROVIDES 'sbsa-acs-drv'

### ISSUE THREAD

**Issue by cipherdev** [ARM-software/arm-enterprise-acs#102]
I see an error when building ACS from master branch. Please help to check. Failed to compile luv-live-image bellow logs: 

> arm-enterprise-acs/luv/build$ bitbake luv-live-image
Loading cache: 100% |###########################################################################################################################| Time: 0:00:00
Loaded 2098 entries from dependency cache.
Parsing recipes: 100% |#########################################################################################################################| Time: 0:00:01
Parsing of 1476 .bb files complete (1472 cached, 4 parsed). 2103 targets, 125 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'sbsa-acs-drv' (but /home/arm-enterprise-acs/luv/meta-luv/recipes-core/images/core-image-efi-initramfs.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'sbsa-acs-drv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['sbsa-acs-drv']
ERROR: Required build target 'luv-live-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['luv-live-image', 'core-image-efi-initramfs', 'sbsa-acs-drv']
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
arm-enterprise-acs/luv/build$

Also same error when I do command `arm-enterprise-acs$ luvos/scripts/build.sh` 

Build Configuration:
>BB_VERSION           = "1.38.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "aarch64-oe-linux"
MACHINE              = "qemuarm64"
DISTRO               = "luv"
DISTRO_VERSION       = "2.3"
TUNE_FEATURES        = "aarch64"
TARGET_FPU           = ""
meta
meta-poky
meta-yocto-bsp
meta-luv
meta-oe              = "heads/v2.3:a108c20590116f6504cc6271267226b4dc454f8a"

--Regards,

**Comment by edhay** [comment]
Hi @cipherdev ,

    Thank you for reporting the issue. 
It is solved by the below check-in:
https://gitlab.arm.com/linux-arm/linux-acs/-/commit/0489cb09f0c0136a24f33208ed6035ed319cd115

We have verified the latest build on master.
Please try a build from the begining.

Arm Enterprise ACS Support

**Comment by edhay** [comment]
Closing as per the fix
