### ISSUE TITLE
FWTS: ACPI SPCR preconfigured baudrate handling

### ISSUE THREAD

**Issue by semihalf-wojtas-marcin** [ARM-software/arm-enterprise-acs#103]
Please cherry-pick the upstream FWTS patch:
https://kernel.ubuntu.com/git/hwe/fwts.git/commit/?id=2ff5a219f2eb818f11ff48ef2c041b149ea76c63

It fixes handling of the preconfigured baudrate case in the FWTS spcr test case.

**Comment by samerhaj** [comment]
This seems to be merged with https://github.com/ARM-software/arm-enterprise-acs/commit/7897ca9a6d9d795e3c1c8f452c8f452e051c2e90

**Comment by edhay** [comment]
The commit 7897ca9 is a patch for LuvOS.
This request is for a fix in FWTS spcr.c

**Comment by samerhaj** [comment]
Thanks @edhay . Yes this FWTS fix is also needed

**Comment by edhay** [comment]
Hi @samerhaj @semihalf-wojtas-marcin , 

 The solution for FWTS code is merged as part of the commit:
https://github.com/ARM-software/arm-enterprise-acs/commit/47685faa10c7834bf232641283dc50032117e8d5

Enterprise ACS Suport
