### ISSUE TITLE
Verify UEFI Spec through ACS v20.10_REL3.0

### ISSUE THREAD

**Issue by Annabelle-Liu** [ARM-software/arm-enterprise-acs#106]
We use ACS to verify UEFI version, but can’t find ACS v20.10_REL3.0 support which version of UEFI Spec.
But can’t find document describe in ACS v20.10_REL3.0 to support UEFI 2.7.
ACS v20.10_REL3.0: https://github.com/ARM-software/arm-enterprise-acs/releases/tag/v20.10_REL3.0
Could help confirm ACS v20.10_REL3.0 support UEFI 2.7? Any document could prove ACS v20.10_REL3.0 support UEFI 2.7?

**Comment by edhay** [comment]
Hi Annbelle,

Thank you for the question.

We have updated the
https://github.com/ARM-software/arm-enterprise-acs/blob/master/README.md#baselines-for-open-source-software-in-this-release
with "Note: UEFI-SCT is based on edk2-test release edk2-test-stable201910 which supports UEFI Specifications version 2.7. Refer to https://uefi.org/testtools for more details"

Detailed Answer:
The edk2-test release tag: 
https://github.com/tianocore/edk2-test/releases/tag/edk2-test-stable201910
the SCT supports UEFI 2.7.

This is mentioned in the UEFI tools page: https://uefi.org/testtools
"UEFI Self-Certification Test 2.7B"

(For further reference : The patch that mentions the support: 
https://github.com/tianocore/edk2-test/commit/fb0e62796ce7efecc9f09245560ef4495f602333)

From the  below section of README
https://github.com/ARM-software/arm-enterprise-acs/blob/v20.10_REL3.0/README.md#baselines-for-open-source-software-in-this-release
SCT in ACS v20.10_REL3.0 is based on the tag : b558bad25479ec83d43399673d7580294c81c8f8 of https://github.com/tianocore/edk2-test
This is over  edk2-test-stable201910 release

Enterprise ACS Support
