### ISSUE TITLE
Builds not working due to gitlab.arm.com down

### ISSUE THREAD

**Issue by vineethrp** [ARM-software/arm-enterprise-acs#117]
gitlab.arm.com is down for a week I guess and hence linux-acs cannot be cloned due to which builds don't work any more.

Any mirrors for linux-acs?

**Comment by edhay** [comment]
Hi @vineethrp , 
 
   gitlab.arm.com was temporarily offline. The issue was resolved on 20.08.2021 and is functional.
Could you please try the build now. 
There are no mirrors for linux-acs.

Please do reach back to us for any other support.

-Arm Enterprise ACS Support

**Comment by vineethrp** [comment]
Thanks @edhay , build is successful now :-)
