### ISSUE TITLE
sbsa_acs: Unknown symbol ArmExecuteMemoryBarrier

### ISSUE THREAD

**Issue by bcran** [ARM-software/arm-enterprise-acs#123]
Running a version of the Enterprise ACS built from today's (2022-01-12) sources results in an unknown symbol error from sbsa_acs:
```
Running fwts ...
[    13.370000] [-] Arm
[   19.615898] sbsa_acs: Unknown symbol ArmExecuteMemoryBarrier (err 0)
insmod: ERROR: could not insert module /lib/modules/4.18.0-luv/extra/sbsa_acs.ko: Unknown symbol in module
```

**Comment by chetan-rathore** [comment]
Hi @bcran,

We are checking the build failure at our side and will fix it asap.

Apologies for the inconvenience.

Regards,
ACS team
