### ISSUE TITLE
There are some issues about booting LuvOS .

### ISSUE THREAD

**Issue by zhoulvwei** [ARM-software/arm-enterprise-acs#35]
Booting under the UEFI shell  ,it goes into grub and print "error:no such device((hd0)/efi/boot)/EFI/BOOT/grub.cfg".Then set root =(hd0,gpt1,gpt2) and config the grub configuration file manually ,it can continue to boot ,but it  is halted before going into linux shell.

Log:

FS3:\efi\boot\> ls
Directory of: FS3:\efi\boot\
12/14/2017  20:18 <DIR>         2,048  .
12/14/2017  20:18 <DIR>         2,048  ..
12/14/2017  20:18              25,997  blue-luv.jpg
12/14/2017  20:18 <DIR>         2,048  sbsa
12/14/2017  20:18                 495  startup.nsh
12/14/2017  20:18                 409  grub.cfg
12/14/2017  20:18 <DIR>         2,048  sbbr
12/14/2017  20:18             827,456  Shell.efi
12/14/2017  20:18             929,280  bootaa64.efi
          5 File(s)   1,783,637 bytes
          4 Dir(s)
FS3:\efi\boot\> bootaa64.efi
Welcome to GRUB!

error: no such device: ((hd0)/efi/boot)/EFI/BOOT/grub.cfg.
GNU GRUB  version 2.02~beta3

   Minimal BASH-like line editing is supported. For the first word, TAB   

   lists possible command completions. Anywhere else TAB lists possible   

   device or file completions.                                            

grub> ls

(hd0) (hd0,gpt1,gpt2) (hd0,gpt1,gpt1) (hd0,gpt1) (hd1) (hd1,msdos4) 

(hd1,msdos3) (hd1,msdos2) (hd1,msdos1) (hd2) (hd2,gpt3) (hd2,gpt2) (hd2,gpt1) 

(hd3) (hd3,gpt5) (hd3,gpt4) (hd3,gpt3) (hd3,gpt2) (hd3,gpt1) (hd4) 

grub> ls(hd0) 

error: can't find command `ls(hd0)'.

grub> ls (hd0,gpt1,gpt1)/

sbsa_results/ 
grub> ls (hd2,gpt1)/

tables/ dsdt efi/ DSDT.dsl results.log d05-capsule-origin.Cap 

d05-capsule-chver.Cap CapsuleApp.efi acpica-tools-20171110-1.fc28.aarch64.rpm 

dmidecode-3.0-2.aarch64.rpm d03-capsule-chver.Cap d03-capsule-origin.Cap initrd

sbsa_acs.ko sbsa filesystem-le_zlw.cpio.gz initrd-linaro 

grub> ls (hd0,gpt1,gpt2)/

efi/ luv.cfg vmlinuz initrd 

grub> set root=(hd0,gpt1,gpt2)
grub> linux /vmlinuz systemd.log_target=null plymouth.ignore-serial-consoles de
bug crashkernel=512M,high log_buf_len=1M efi=debug acpi=on crashkernel=256M early
con uefi_debug console=ttyAMA0 luv_netconsole=${LUV_NETCONSOLE} luv_storage=${L
UV_STORAGE_URL} 
grub> initrd /initrd
grub> boot
EFI stub: Booting Linux Kernel...
EFI stub: Using DTB from configuration table
EFI stub: Exiting boot services and installing virtual address map...
........
......
.......
.......
.......
[  264.332601] pci_generic_config_write32: 133 callbacks suppressed
[  264.344706] pci_bus 000d:30: 2-byte config write to 000d:30:00.0 offset 0x44 may corrupt adjacent RW1C bits
[  264.344706] pci_bus 000d:30: 2-byte config write to 000d:30:00.0 offset 0x44 may corrupt adjacent RW1C bits
[  264.381311] pci_bus 000d:30: 2-byte config write to 000d:30:00.0 offset 0x78 may corrupt adjacent 
[  264.518927] pci_bus 000a:10: 2-byte config write to 000a:10:00.0 offset 0x44 may corrupt adjacent RW1C bits
[  264.518927] pci_bus 000a:10: 2-byte config write to 000a:10:00.0 offset 0x44 may corrupt adjacent RW1C bits
[  264.557305] pci_bus 000a:10: 2-byte config write to 000a:10:00.0 offset 0x78 may corrupt adjacent RW1C bits
[  264.557305] pci_bus 000a:10: 2-byte config write to 000a:10:00.0 offset 0x78 may corrupt adjacent RW1C bits
[  264.653665] reboot: System halted
[  264.653665] reboot: System halted

**Comment by prasanth-pulla** [comment]
Closing this issue as we are not seeing this issue anymore with the new firmware/software combination and ACS version 1.6.
