### ISSUE TITLE
No simple way to fetch images

### ISSUE THREAD

**Issue by hrw** [ARM-software/arm-enterprise-acs#71]
```
~ $ cd arm-enterprise-acs-20.03_REL2.4/prebuilt_images/v20.03_REL2.4/
v20.03_REL2.4 $ ls -l
razem 8
-rw-rw-r--. 1 hrw hrw 134 03-27 06:44 luv-live-image-gpt.img
-rw-rw-r--. 1 hrw hrw 134 03-27 06:44 PXEBOOT.tar.gz
```

Readme says "use git lfs pull"...

```
v20.03_REL2.4 $ git lfs pull
Not in a git repository.
```

So I cloned git repo. Started "git lfs pull" and got nothing.

I prefer to fetch prebuilt image rather than spending time on getting it build on some ancient ubuntu version. But looks like someone decided to not make it possible.

**Comment by edhay** [comment]
Hello Marcin,

    Thank you for the query

Before doing the 
git lfs pull
did you follow the step mentioned in the https://github.com/ARM-software/arm-enterprise-acs/blob/release/prebuilt_images/README.md to install the 'git lfs' tool?

_All pre-built image(s) have been uploaded using git lfs tool. Refer to http://git-lfs.github.com for information on installing git lfs tool._ 

I have verified 
git lfs pull 
command after your query. It is working fine.

**Comment by hrw** [comment]
```
$ docker run -it -u root debian:buster
# cd;apt update;apt install -y wget git-lfs
# wget https://github.com/ARM-software/arm-enterprise-acs/archive/v20.03_REL2.4.tar.gz
# tar xf v20.03_REL2.4.tar.gz
# cd arm-enterprise-acs-20.03_REL2.4/prebuilt_images/v20.03_REL2.4/
root@f6f27fa4ce36:~/arm-enterprise-acs-20.03_REL2.4/prebuilt_images/v20.03_REL2.4# git lfs pull
Not in a git repository.
root@f6f27fa4ce36:~/arm-enterprise-acs-20.03_REL2.4/prebuilt_images/v20.03_REL2.4# cd ..
root@f6f27fa4ce36:~/arm-enterprise-acs-20.03_REL2.4/prebuilt_images# git lfs pull
Not in a git repository.
root@f6f27fa4ce36:~/arm-enterprise-acs-20.03_REL2.4/prebuilt_images# cd ..
root@f6f27fa4ce36:~/arm-enterprise-acs-20.03_REL2.4# git lfs pull
Not in a git repository.
root@f6f27fa4ce36:~/arm-enterprise-acs-20.03_REL2.4# 
```

Can not present it simpler that it does not work.

**Comment by edhay** [comment]
Thank you for the details.

The 'git lfs pull' will work only in an active git repository and not on a downloaded tar ball of code.

The 'git clone' of the repository must be done.
Please follow the below steps.
  
  $ git clone https://github.com/ARM-software/arm-enterprise-acs.git
  $ cd arm-enterprise-acs/

  $ git checkout release
  $ cd prebuilt_images/

  $ cd v20.03_REL2.4/
  $ git lfs pull

**Comment by hrw** [comment]
So add this information to release note and to readme in tarball.

**Comment by edhay** [comment]
Thank you for the suggestion. 
We will add this information in the Release Notes and README.

**Comment by edhay** [comment]
The information is added here:
https://github.com/ARM-software/arm-enterprise-acs/blob/release/prebuilt_images/README.md

"Please Note: The 'git lfs pull' will work only in an active git repository. Please clone this repo and switch to 'release' branch."
