### ISSUE TITLE
fix bison build with new libc

### ISSUE THREAD

**Issue by leiflindholm** [ARM-software/arm-enterprise-acs#73]
Same cause as [the m4 issue](https://github.com/ARM-software/arm-enterprise-acs/issues/72), build fails with:
```
| ../bison-3.0.4/lib/fseterr.c: In function 'fseterr':
| ../bison-3.0.4/lib/fseterr.c:77:3: error: #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
|   #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
|    ^~~~~
```

A seemingly functional fix can be found at https://github.com/rdslw/openwrt/blob/e5d47f32131849a69a9267de51a30d6be1f0d0ac/tools/bison/patches/110-glibc-change-work-around.patch

**Comment by edhay** [comment]
Solution verification is in progress.
The fix will be incorporated in the upcoming Enterprise ACS v3.0

**Comment by bcran** [comment]
I've tested this on Ubuntu 20.04 and the build now succeeds.

**Comment by edhay** [comment]
Closing this issue as per confirmation from @bcran.

**Comment by shravan56** [comment]
> I've tested this on Ubuntu 20.04 and the build now succeeds.

Can u please explain how u applied this patch after download?
(patch: https://github.com/rdslw/openwrt/blob/e5d47f32131849a69a9267de51a30d6be1f0d0ac/tools/bison/patches/110-glibc-change-work-around.patch)

**Comment by bcran** [comment]
I'm not sure I did. I just ran the build and it worked.

**Comment by shravan56** [comment]
> Same cause as [the m4 issue](https://github.com/ARM-software/arm-enterprise-acs/issues/72), build fails with:
> 
> ```
> | ../bison-3.0.4/lib/fseterr.c: In function 'fseterr':
> | ../bison-3.0.4/lib/fseterr.c:77:3: error: #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
> |   #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
> |    ^~~~~
> ```
> 
> A seemingly functional fix can be found at https://github.com/rdslw/openwrt/blob/e5d47f32131849a69a9267de51a30d6be1f0d0ac/tools/bison/patches/110-glibc-change-work-around.patch

Can u please explain how u applied this patch after download?

**Comment by XiaowenHu96** [comment]
@shravan56 
I applied the patch under `bison-3.0.4/lib`

**Comment by divinity76** [comment]
@shravan56 basically
```
wget 'http://ftp.gnu.org/gnu/bison/bison-2.7.tar.xz'
tar xfv bison-2.7.tar.xz
cd bison-2.7
wget 'https://raw.githubusercontent.com/rdslw/openwrt/e5d47f32131849a69a9267de51a30d6be1f0d0ac/tools/bison/patches/110-glibc-change-work-around.patch' -O- \
 | git apply -
mkdir -pv [bison_bin_dir]
./configure --prefix=[bison_bin_dir]
make -j $(nproc)
make install
```
