### ISSUE TITLE
Some warnings when building ACS from master branch

### ISSUE THREAD

**Issue by nhivp** [ARM-software/arm-enterprise-acs#78]
I see the following warnings when building ACS from master branch. Please help to check.

Warning 1:
```
Default kernel command line parameters: 'systemd.log_target=null plymouth.ignore-serial-consoles debug ip=dhcp log_buf_len=1M efi=debug acpi=on crashkernel=256M earlycon uefi_debug'
Append parameters (press Enter for default):
Building all modules
WARNING: /home/npham/temp/build-acs/arm-enterprise-acs/luv/meta-luv/recipes-core/sdei-acs-val/sdei-acs-val_0.1.bb: Getting checksum for sdei-acs-val SRC_URI entry : file not found except in DL_DIR:00:17
WARNING: /home/npham/temp/build-acs/arm-enterprise-acs/luv/meta-luv/recipes-kernel/linux/linux-luv_4.18.bb: Unable to get checksum for linux-luv SRC_URI entry 0001-Enterprise-acs-linux-v4.18.patch: file could not be found
Parsing recipes: 100% |####################################################################################################################################################################| Time: 0:00:35
Parsing of 1476 .bb files complete (0 cached, 1476 parsed). 2103 targets, 125 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
```

Warning 2:
```
WARNING: popt-native-1.16-r3 do_fetch: Failed to fetch URL https://fossies.org/linux/misc/popt-1.16.tar.gz, attempting MIRRORS if available
```

Build Configuration:
BB_VERSION           = "1.38.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "aarch64-oe-linux"
MACHINE              = "qemuarm64"
DISTRO               = "luv"
DISTRO_VERSION       = "2.3"
TUNE_FEATURES        = "aarch64"
TARGET_FPU           = ""

**Comment by nhivp** [comment]
Failed to build with my fresh machine (Ubuntu 18.04).
[build-acs-error.log](https://github.com/ARM-software/arm-enterprise-acs/files/5251359/build-acs-error.log)

**Comment by edhay** [comment]
Hi,

    Thank you for the query.

Regarding the warnings you have listed above, they may be ignored. The build system is trying to reach the mirror sites if the main site is unavailable. That will have no impact on your build.

Regarding the build-acs-error.log:
We notice this command:
wget -nv "https://releases.linaro.org/components/toolchain/binaries/4.9-2016.02/aarch64-linux-gnu/gcc-linaro-4.9-2016.02-x86_64_aarch64-linux-gnu.tar.xz
failing.

Probably there was a temporary issue in the internet connection. This is leading to later failures.
Could you please run this command on the command-line and check if its okay.


--Enterprise ACS Support

**Comment by nhivp** [comment]
Yeah, thanks @edhay 

It works for me now.

Below are the commands I used to build:

```
# ./acs_sync.sh
# luvos/scripts/build.sh
```
