### ISSUE TITLE
Build fails with message "ERROR: Function failed: build_hddimg"

### ISSUE THREAD

**Issue by PrashantSangal01** [ARM-software/arm-enterprise-acs#81]
Hi, 

I am trying to build luv-live-image from branch "test-integration". As per instructions, an x86_64 machine runnning Ubuntu-18.04 is used. Please check following: 

../arm-enterprise-acs$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

../arm-enterprise-acs$ uname -a
Linux prashant-PC 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Following commands are used to build the package: 
../arm-enterprise-acs$ ./acs_sync.sh
../arm-enterprise-acs$ ./luvos/scripts/build.sh

The build process fails with following message ( complete log message is attached as [ACS-3.0-build-failure.LOG](https://github.com/ARM-software/arm-enterprise-acs/files/5342189/ACS-3.0-build-failure.LOG) )::

| DEBUG: Executing shell function build_hddimg
| NOTE: Trying to install /home/prashant/workspace/ACS_07Oct/arm-enterprise-acs/luv/build/tmp/deploy/images/qemuarm64/Image as /home/prashant/workspace/ACS_07Oct/arm-enterprise-acs/luv/build/tmp/work/aarch64-oe-linux/luv-live-image/1.0-r0/hddimg/Image
| Including UEFI-SCT
| cp: cannot stat '/home/prashant/workspace/ACS_07Oct/arm-enterprise-acs/luv/build/tmp/deploy/images/qemuarm64/sbsa': No such file or directory
| WARNING: exit code 1 from a shell command.
| DEBUG: Python function do_bootimg finished
| ERROR: Function failed: build_hddimg (log file is located at /home/prashant/workspace/ACS_07Oct/arm-enterprise-acs/luv/build/tmp/work/aarch64-oe-linux/luv-live-image/1.0-r0/temp/log.do_bootimg.7624)
ERROR: Task (/home/prashant/workspace/ACS_07Oct/arm-enterprise-acs/luv/meta-luv/recipes-core/images/luv-live-image.bb:do_bootimg) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3418 tasks of which 2306 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/prashant/workspace/ACS_07Oct/arm-enterprise-acs/luv/meta-luv/recipes-core/images/luv-live-image.bb:do_bootimg
Summary: There were 2 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
Build failed...

On checking log.do_bootimg.7624 ( attached as [log.do_bootimg.7624.LOG](https://github.com/ARM-software/arm-enterprise-acs/files/5342191/log.do_bootimg.7624.LOG)), the error reported is as following: 
ERROR: Function failed: build_hddimg

Also, it seems that the script fails to create sbsa folder in build folder: 
cp: cannot stat '/home/prashant/workspace/ACS_07Oct/arm-enterprise-acs/luv/build/tmp/deploy/images/qemuarm64/sbsa': No such file or directory

If it is created manually, the build fails with more errors. 

Regards, 
Prashant Sangal

**Comment by edhay** [comment]
Hi Prashant,

   Please use the 'master' branch for build. Please do contact us for any clarifications.
Closing this issue.

-- Enterprise ACS Support
