### ISSUE TITLE
MPAM - Broken embedded link

### ISSUE THREAD

**Issue by ramymdsc** [ARM-software/arm-enterprise-acs#84]
**Version**: v20.08_REL2.5
**Affected File**: arm-enterprise-acs/mpam/README.md

**Description**: under _Release details_, the _Scenario Document_ embedded link is broken.
**Solution**: amend link to point to _Arm_MPAM_ACS_Scenario_Document.pdf_ instead of _Mpam_ACS_Scenario_document.pdf_.

**Comment by edhay** [comment]
Thank you for the feedback. This is updated in the latest code.

-- Enterprise ACS Support
