### ISSUE TITLE
SBSA/SBBA linux tests has different test cases with LuvOS 

### ISSUE THREAD

**Issue by yaroslav-pushko** [ARM-software/arm-enterprise-acs#92]
During performing tests I noticed that there is a difference between Linux test launch from sbsa/sbbr grub option and LuvOS.
I use: luv-live-image-gpt_v20.08_REL2.5.img

For examaple:
grub.cfg: luv -> luv_tests=${LUV_TESTS}, 
where luv.cfg:"set LUV_TESTS='efivarfs-test,fwts,kernel-efi-warnings,pstore-tests,'"

but in startup.nsh -> luv_tests=fwts

**Comment by edhay** [comment]
Hi Yaroslav,

    Thank you for the observation. We will make grub.cfg equivalent to startup.nsh luv_tests.
Only FWTS shall be invoked in both cases.

Enterprise ACS Support

**Comment by edhay** [comment]
Hi Yaoslav,

Through the commit : https://github.com/ARM-software/arm-enterprise-acs/commit/c548014c96502d98b46ae9f7c7934ecd26c48b93
the LUV_TESTS is made equivalent in case of grub.cfg and startup.nsh.

In both cases only FWTS tests will be run.

Enterprise ACS Support
