### ISSUE TITLE
Consider forking luv-yocto to simplify maintenance?

### ISSUE THREAD

**Issue by bcran** [ARM-software/arm-enterprise-acs#99]
With https://github.com/intel/luv-yocto being fixed in time and no longer maintained, I wonder if it might make sense to fork it and commit fixes and changes needed to support the Enterprise ACS directly, instead of creating patches that get applied at various times during the checkout/build stages?

**Comment by edhay** [comment]
Hi Rebecca, 

Thank you for your suggestion.

In the new ACS for BSA and BBR (currently in Alpha and Beta), we have moved away from LuvOS. 
There is a plan to adapt SBSA and SBBR to the new code structure of BSA and BBR.
So we don't want change the build method or maintain a seperate fork at this point of time.

--Enterprise ACS Support
